apiVersion: apps/v1
kind: Deployment

metadata:
  name: cicd-security-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cicd-security-app

  template:
    metadata:
      labels:
        app: cicd-security-app

    spec:
      containers:
        - name: cicd-security-app
          image: kadambari0809/cicd-security-app:1.0
          imagePullPolicy: Always
