apiVersion: v1
kind: Service

metadata:
  name: cicd-security-service

spec:
  type: NodePort

  selector:
    app: cicd-security-app

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
